### ISSUE TITLE
Production build fails using ng build  --prod

### ISSUE THREAD

**Issue by skesani** [RenovoSolutions/ngx-datetimepicker#88]
**Compiles successfully when runs `ng serve`, but the build fails when using** `ng build  --prod`
**Below are my dependencies**

``` "dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "^5.0.0",
    "@ng-idle/core": "^2.0.0-beta.15",
    "@ng-idle/keepalive": "^2.0.0-beta.15",
    "@okta/okta-signin-widget": "^2.21.0",
    "ag-grid-angular": "^21.2.2",
    "ag-grid-community": "^21.2.2",
    "ag-grid-enterprise": "^21.2.2",
    "angular-tree-component": "^8.4.0",
    "bootstrap": "4.2.1",
    "core-js": "^2.6.9",
    "file-saver": "^2.0.2",
    "lodash": "^4.17.15",
    "ngx-bootstrap": "^3.3.0",
    "ngx-datetime-picker": "^3.0.0",
    "ngx-order-pipe": "^2.0.3",
    "npm": "^6.11.2",
    "popper.js": "^1.14.7",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "sweetalert2": "^8.16.3",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "~7.1.0",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }```

```
ERROR in ./node_modules/ngx-datetime-picker/fesm5/ngx-datetime-picker.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
at isAngularDecoratorMetadataExpression (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
at visitNodes (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16144:30)
at Object.forEachChild (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16370:24)
at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16265:21)
at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16322:24)
at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16333:24)
at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16229:21)
at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNodes (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16144:30)
at Object.forEachChild (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16379:24)
at checkNodeForDecorators (/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
at visitNode (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16135:24)
at Object.forEachChild (/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16377:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tmssclient@0.0.0 buildProd: `ng --prod build`
npm ERR! Exit status 1
npm ERR!
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
npm ERR!    /.npm/_logs/2019-11-17T21_27_04_106Z-debug.log

```

**Comment by eltiare** [comment]
I'm having this issue as well.

**Comment by skesani** [comment]
@JoshDSommer can you please take a look at this issue?

**Comment by jrquick17** [comment]
Are you both Angular 7 as well? @skesani @eltiare 

It works in ng8.

**Comment by skesani** [comment]
> Are you both Angular 7 as well? @skesani @eltiare
> 
> It works in ng8.

Yes @jrquick17 I am using Angular 7  and we can't migrate to Angular 8 at this point, I am looking for a solution for Angular 7.

**Comment by jrquick17** [comment]
It is most likely a problem with the new packaging (ng-packagr). I will try and take a look and see what I can do. In the meantime I would recommend using version 2.1.3.

`npm install ngx-datetime-picker@2.1.3 --save`

**Comment by eltiare** [comment]
I got it to build by disabling the AOT build in Angular's json settings file. Not sure of what version of angular I'm running.

**Comment by skesani** [comment]
@jrquick17 Is there an input change event in the datetimepicker?
Also, right now the time is the increment of 5 10, 15, etc.... how to change it to 1,2,3...
Example: I can't select 12:53 it allowing me to select increments of 5, i.e, 12:55 ...

![image](https://user-images.githubusercontent.com/2635028/69173236-622e5b00-0acd-11ea-9bd0-b50290d8e8f7.png)

**Comment by andsilver** [comment]
`ERROR in Internal Error: Unexpected interpolation`

With Angular 9, I am getting the error while build.
I use ngx-datetime-picker@2.1.3

Could you please help me?

**Comment by benjamin-a-kuntz** [comment]
Project now officially supports only Angular 12 - this does not appear to be a problem in this version.
